<!DOCTYPE html>
<html>
<script>
    let promise = new Promise(function (resolve, reject) {
        setTimeout(() => resolve("done"), 1000);
        // setTimeout(() => reject(new Error("Whoops!")), 1000);
    });
    // Consumers: then, catch
    promise.then(
        result => alert("result gotcha!"),
        error => alert(error),
    );

    // If we’re interested only in successful completions, then we can provide only one function argument to .then:
    promise.then(alert);

    /*
    catch
    If we’re interested only in errors, then we can use null as the first argument: .then(null, errorHandlingFunction). Or we can use .catch(errorHandlingFunction), which is exactly the same:
    */
    // .catch(f) is the same as promise.then(null, f)
    promise.catch(alert);

    // Cleanup: finally
    new Promise((resolve, reject) => {
        setTimeout(() => resolve("value"), 2000);
    })
        .finally(() => alert("Promise ready")) // triggers first
        .then(result => alert(result))
        .catch(err => alert(err));
</script>

</html>